# This is a basic workflow to help you get started with Actions
name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'https://github.com/2pisoftware/cmfive-boilerplate'
          ref: 'refs/branch/feature/cicd'

      # Build cmfive containers
      - name: Build cmfive
        run: |
          cp config.example.php config.php
          cd "$GITHUB_WORKSPACE/.build/setup"
          python3 -m venv venv;
          source venv/bin/activate;
          pip install -r requirements.txt;
          python3 install.py provision-test;
          docker start selenium314
      - name: Test cmfive
        run: |
          docker exec nginx-php7.2 php cmfive.php testDB setup
          docker exec nginx-php7.2 php cmfive.php tests unit all
          docker exec nginx-php7.2 php cmfive.php test run all
